<?php

namespace Database\Seeders;

use App\Models\Produit;
use Illuminate\Database\Seeder;

class ProduitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produits = [
    // --- PHOTO 1 (WhatsApp Image 2026-06-16 at 07.08.28.jpeg) ---
    ['nom' => 'Ecrou 17 simple', 'reference' => 'ECU0000', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Boulon 17/60 Complet', 'reference' => 'BAN0001', 'prix_achat' => 85, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 13/20 Complet', 'reference' => 'BLN0002', 'prix_achat' => 35, 'prix_vente' => 100, 'image' => null], // Prix client déduit du doublon plus bas
    ['nom' => 'Boulon 13/35 Complet', 'reference' => 'BLN0003', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Ecrou 17 de laxe', 'reference' => 'ECU0004', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Attache chaine', 'reference' => 'ATC0005', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Fusible simple', 'reference' => 'FSB0006', 'prix_achat' => 20, 'prix_vente' => 40, 'image' => null],
    ['nom' => 'Ecrou 13 Simple', 'reference' => 'ECU0007', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Rondelle 10', 'reference' => 'RDL0008', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 10/25 Complet', 'reference' => 'BLN0009', 'prix_achat' => 25, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Rondelle 8', 'reference' => 'RDL0010', 'prix_achat' => 20, 'prix_vente' => 30, 'image' => null],
    ['nom' => 'Boulon 17/40', 'reference' => 'BLN0011', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 10/25 Simple', 'reference' => 'BLN0012', 'prix_achat' => 20, 'prix_vente' => 30, 'image' => null],
    ['nom' => 'Rondelle 13 Petit', 'reference' => 'RDL0013', 'prix_achat' => 25, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 13/70 Complet', 'reference' => 'BLN0014', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Rondelle 17 Petit', 'reference' => 'RDL0015', 'prix_achat' => 40, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 10/60 Simple', 'reference' => 'BLN0016', 'prix_achat' => 30, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulon 10/60 Complet', 'reference' => 'BLN0017', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulon 17/60 Complet (v2)', 'reference' => 'BLN0018', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Boulon 13/20 Simple', 'reference' => 'BLN0019', 'prix_achat' => 25, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 13/60 Complet', 'reference' => 'BLN0020', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Ecrou 13 simple (v2)', 'reference' => 'ECU0021', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulon 10/10 Simple', 'reference' => 'BLN0022', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Ecrou 14 chapeau', 'reference' => 'ECU0023', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Cale Petit Pignon GN', 'reference' => 'CPP0024', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Cale Petit Pignon Bj/TVS', 'reference' => 'CPP0025', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],

        // À remplacer ou insérer dans votre ProduitSeeder.php (Section Photo 2)
    ['nom' => 'Rondelle 17 Gros', 'reference' => 'BDL0026', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Arrêt d\'huile Soupape TVS', 'reference' => 'AHS0027', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Ecrou 19 de laxe', 'reference' => 'ECU0028', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulong 8/10 Complet', 'reference' => 'BLN0029', 'prix_achat' => 20, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Arrêt d\'huile Soupape GN', 'reference' => 'AHS0030', 'prix_achat' => 40, 'prix_vente' => 75, 'image' => null],
    ['nom' => 'Boulong Vidange TVS', 'reference' => 'BLN0031', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Bouchong Couvre Chaine CGL', 'reference' => 'BCC0032', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Arrêt d\'huile 12-22 (LV TVS)', 'reference' => 'AHL0033', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arrêt d\'huile 14-28 (LV 150)', 'reference' => 'AHL0034', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arrêt d\'huile 16-28', 'reference' => 'AHL0035', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arrêt d\'huile 16-26', 'reference' => 'AHL0036', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Arrêt d\'huile 13-22', 'reference' => 'AHL0037', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Sère Cable', 'reference' => 'SCS0038', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Arrêt d\'huile 17-29', 'reference' => 'AHL0039', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Boulong 10/10 Simple', 'reference' => 'BLN0040', 'prix_achat' => 25, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Yamalube 4T', 'reference' => 'YLB0041', 'prix_achat' => 3025, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'huil TVS', 'reference' => 'HLT0042', 'prix_achat' => 3200, 'prix_vente' => 3400, 'image' => null],
    ['nom' => 'huil elf', 'reference' => 'HLE0043', 'prix_achat' => 2750, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'huil standard', 'reference' => 'HLS0044', 'prix_achat' => 2500, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Boulong 8/10 Simple', 'reference' => 'BLN0045', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Rondel 19', 'reference' => 'RDL0046', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Boulong 8/30 Complet', 'reference' => 'BLN0047', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Garniture GN 3Z & W6', 'reference' => 'GNT0048', 'prix_achat' => 550, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Garniture TVS 3Z & W6', 'reference' => 'GNT0049', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Garniture TVS SM', 'reference' => 'GNT0050', 'prix_achat' => 800, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Boulong 10/20 Simple', 'reference' => 'BNT0051', 'prix_achat' => 20, 'prix_vente' => 50, 'image' => null],
    ['nom' => 'Boulong 10/20 Complet', 'reference' => 'BLN0052', 'prix_achat' => 20, 'prix_vente' => 75, 'image' => null],

    // --- PHOTO 3 (WhatsApp Image 2026-06-16 at 07.09.56.jpeg) ---
    ['nom' => 'Bouchong Couvre chaine Baja', 'reference' => 'BCN0053', 'prix_achat' => 100, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Garniture CG125 3Z & W8', 'reference' => 'GNC0054', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Garniture TVS 3M & W6', 'reference' => 'GNT0055', 'prix_achat' => 700, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Garniture TVS 3Z & W8', 'reference' => 'GNT0056', 'prix_achat' => 500, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Retroviseur Baja SM', 'reference' => 'RTS0057', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Retroviseur GGL125 Mr Li', 'reference' => 'RTS0058', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Retroviseur GN125 SM', 'reference' => 'RTS0059', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Levier Vitesse Tvs', 'reference' => 'LVT0060', 'prix_achat' => 600, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Demareur a pied CG (Samli)', 'reference' => 'DPC0061', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Demareur a pied CGL (Senke)', 'reference' => 'DPC0062', 'prix_achat' => 900, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Demareur a pied Baja', 'reference' => 'DPB0063', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Demareur a pied Tvs', 'reference' => 'DPT0064', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Demareur a pied 200 1T', 'reference' => 'DPN0065', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Axe Grand bequille CGL', 'reference' => 'AGB0066', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe Grand bequille GN', 'reference' => 'AGB0067', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe Arriere CGL (Senke)', 'reference' => 'AAC0068', 'prix_achat' => 450, 'prix_vente' => 750, 'image' => null],
    ['nom' => 'Axe Arriere GN (P6)', 'reference' => 'AAG0069', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe Arriere TVS', 'reference' => 'AAT0070', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe Avant Baja', 'reference' => 'AAB0071', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe demi Chassi Baja', 'reference' => 'ADC0072', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Axe Avant CGL (Senke)', 'reference' => 'AAC0073', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Axe Arriere Hight Jack', 'reference' => 'AAH0074', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Bouchong Vidange 150', 'reference' => 'BCV0075', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Lazer WDFR Tete verte', 'reference' => 'LVT0076', 'prix_achat' => 1300, 'prix_vente' => 1600, 'image' => null],
    ['nom' => 'Lazer SM Tete verte', 'reference' => 'LVT0077', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],

    // --- PHOTO 4 (WhatsApp Image 2026-06-16 at 10.12.36.jpeg) ---
    ['nom' => 'Manette de frein Senke', 'reference' => 'MDF0078', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Manette d\'embrayage Baja', 'reference' => 'MDB0079', 'prix_achat' => 275, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Manette d\'embrayage GN', 'reference' => 'MDG0080', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Lazer SM 12V-6T (noir)', 'reference' => 'LSM0081', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Huile Darsoncy SAE 50', 'reference' => 'HDS0082', 'prix_achat' => 1300, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Huile Ayanol 4T', 'reference' => 'HAY0083', 'prix_achat' => 2500, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Huile Yamalub Pirogue 2', 'reference' => 'HYP0084', 'prix_achat' => 4050, 'prix_vente' => 4500, 'image' => null],
    ['nom' => 'Huile de direction ATF', 'reference' => 'HDD0085', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Spray ABRO rouge', 'reference' => 'SAR0086', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray ABRO Jaune', 'reference' => 'SAJ0087', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Spray Pro Loc blanc', 'reference' => 'SPB0088', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Huil de Frein GM', 'reference' => 'HDF0089', 'prix_achat' => 850, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Instinteur 500mL Abro', 'reference' => 'IAG0090', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Baterie 12N6 (senke)', 'reference' => 'BTS0091', 'prix_achat' => 5600, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Tuyau de Carburant', 'reference' => 'TDC0092', 'prix_achat' => 20, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Clé Contact CGL SM', 'reference' => 'CCC0093', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Clé Contact CGL J&H', 'reference' => 'CCJ0094', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Clé Contact TVS SM', 'reference' => 'CCT0094', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null], // Doublon partiel de référence sur manuscrit, conservé tel quel
    ['nom' => 'Carburateur 150 SM', 'reference' => 'CBT0095', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Clé Contact Baja hongcheng', 'reference' => 'CCB0096', 'prix_achat' => 1600, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Clé Contact Baja 3M&W6', 'reference' => 'CCB0097', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Clé Contact Baja SM', 'reference' => 'CCB0098', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Carburateur TVS TKS', 'reference' => 'CCT0099', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Cable d\'accélérateur Baja', 'reference' => 'CDB0100', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Vilbregain WDFR TVS', 'reference' => 'VWD0101', 'prix_achat' => 8000, 'prix_vente' => 8800, 'image' => null],
    ['nom' => 'Vilbregain SM 150', 'reference' => 'VSM0102', 'prix_achat' => 8500, 'prix_vente' => 9300, 'image' => null],

    // --- PHOTO 5 (IMG-20260616-WA0037.jpg) ---
    ['nom' => 'Resor grand bequille GN', 'reference' => 'RGB0103', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Resor grand bequille CGL', 'reference' => 'RGB0104', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Segment Baja', 'reference' => 'SGB0105', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Vilbregain Baja SM', 'reference' => 'VBQ0106', 'prix_achat' => 8500, 'prix_vente' => 9200, 'image' => null],
    ['nom' => 'Vilbregain TVS YOG', 'reference' => 'VBT0107', 'prix_achat' => 9500, 'prix_vente' => 10500, 'image' => null],
    ['nom' => 'Soupape Baja YOG', 'reference' => 'SBY0108', 'prix_achat' => 800, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Soupape Baja SM', 'reference' => 'SBS0109', 'prix_achat' => 450, 'prix_vente' => 850, 'image' => null],
    ['nom' => 'Soupape CD10', 'reference' => 'SCD0110', 'prix_achat' => 450, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Huile Maxalub 20W-50', 'reference' => 'HML0111', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Huil National Jaune 20W-50', 'reference' => 'HNJ0112', 'prix_achat' => 3100, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Sandaux', 'reference' => 'SDX0113', 'prix_achat' => 125, 'prix_vente' => 250, 'image' => null],
    ['nom' => 'Soupape TVS SM', 'reference' => 'STS0114', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Segment 150 SM STD +', 'reference' => 'SGS0115', 'prix_achat' => 650, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Piston CD110 STD + SM', 'reference' => 'PCD0116', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS STD + SM', 'reference' => 'PTS0117', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS STD ++ JYC', 'reference' => 'PTS0118', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS STD + 3M&W6', 'reference' => 'PTS0119', 'prix_achat' => 1600, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Poignier d\'allumage CGL Gauche', 'reference' => 'PCO0120', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Poignier d\'allumage Complet Côté G', 'reference' => 'PDG0121', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Poig long Resor', 'reference' => 'LRS0122', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Pignong Arriere CB-125', 'reference' => 'PAC0123', 'prix_achat' => 1250, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Transmission CB-125', 'reference' => 'TCB0124', 'prix_achat' => 4000, 'prix_vente' => 4500, 'image' => null],
    ['nom' => 'Pignon Arrière GN 3M', 'reference' => 'PAG0125', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],

    // --- PHOTO 6 (WhatsApp Image 2026-06-16 at 23.44.30.jpeg) ---
    ['nom' => 'Transmission Bj 3M&W6', 'reference' => 'TBM0130', 'prix_achat' => 3350, 'prix_vente' => 3900, 'image' => null],
    ['nom' => 'Pôt de for Baja', 'reference' => 'PFB0131', 'prix_achat' => 2800, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Pôt de for CG125 (Long chassi)', 'reference' => 'PDF0132', 'prix_achat' => 3200, 'prix_vente' => 3800, 'image' => null],
    ['nom' => 'Pôt de for TVS', 'reference' => 'PFT0133', 'prix_achat' => 2700, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Pignong arriere Baja', 'reference' => 'PAB0134', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignong arriere WY-CG 4D', 'reference' => 'PAW0135', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pneu CST 300-18 NC', 'reference' => 'PNC0136', 'prix_achat' => 12000, 'prix_vente' => 15000, 'image' => null],
    ['nom' => 'Pneu CST 350-16 NC', 'reference' => 'PNC0136-2', 'prix_achat' => 13500, 'prix_vente' => 17000, 'image' => null], // Même référence sur papier, ajusté pour distinction
    ['nom' => 'Pneu 275-17 local', 'reference' => 'PNL0137', 'prix_achat' => 4700, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'Pneu 275-18 local', 'reference' => 'PNL0138', 'prix_achat' => 4700, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'Pneu 275-17 CST', 'reference' => 'PNL0139', 'prix_achat' => 12000, 'prix_vente' => 12600, 'image' => null],
    ['nom' => 'Pneu 300-18 local', 'reference' => 'PNL0140', 'prix_achat' => 5500, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Pneu 300-17 local', 'reference' => 'PNL0141', 'prix_achat' => 5500, 'prix_vente' => 6000, 'image' => null],
    ['nom' => 'Garniture 200 Grand Model', 'reference' => 'GGM0142', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Garniture 200 Petit Model', 'reference' => 'GPM0143', 'prix_achat' => 1500, 'prix_vente' => 1900, 'image' => null],
    ['nom' => 'Roulement 6201', 'reference' => 'RLT0144', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6204', 'reference' => 'RLT0145', 'prix_achat' => 325, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Roulement 6304', 'reference' => 'RLT0146', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Roulement 6001', 'reference' => 'RLT0147', 'prix_achat' => 200, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6800', 'reference' => 'RLT0148', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6004', 'reference' => 'RLT0149', 'prix_achat' => 220, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Roulement 6200', 'reference' => 'RLT0150', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Roulement 6202', 'reference' => 'RLT0151', 'prix_achat' => 180, 'prix_vente' => 350, 'image' => null],
    ['nom' => 'Demareur automatique CG200', 'reference' => 'RLT0152', 'prix_achat' => 5000, 'prix_vente' => 5500, 'image' => null],
    ['nom' => 'Segment CG200 STD +', 'reference' => 'SGG0153', 'prix_achat' => 800, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Petit lecteur', 'reference' => 'PLK0154', 'prix_achat' => 4700, 'prix_vente' => 5300, 'image' => null],

    // --- TRIPLET DE FICHES (FICHES 7, 8 & 9) ---
    ['nom' => 'Plaquette frein GN', 'reference' => 'PFG0155', 'prix_achat' => 275, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Amponle Ronde', 'reference' => 'ARN0156', 'prix_achat' => 120, 'prix_vente' => 250, 'image' => null],
    ['nom' => 'Bille de guidong Tvs', 'reference' => 'BDG0157', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Bille de guidong Baja', 'reference' => 'BDG0158', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Petit Clakson', 'reference' => 'PTC0159', 'prix_achat' => 500, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Gros Clakson', 'reference' => 'GSC0160', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Chargeur 150', 'reference' => 'CHA0161', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pignong Marche arriere 200 13T', 'reference' => 'PMA0162', 'prix_achat' => 1200, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Pignong Marche arriere 200 11T', 'reference' => 'PMA0163', 'prix_achat' => 1200, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Pignong Marche arriere 200 12T', 'reference' => 'PMA0164', 'prix_achat' => 1200, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Guide Soupape 150', 'reference' => 'GSP0165', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Guide Soupape Tvs TP oem', 'reference' => 'GST0166', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Guide Chaine Moteur 25H-88L', 'reference' => 'CHM0167', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable d\'ambreyage Tvs', 'reference' => 'CDT0167', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable de frein Bajaj', 'reference' => 'CDF0168', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pair de Capeau Senke', 'reference' => 'CAS0169', 'prix_achat' => 2000, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Ver de phare Senke', 'reference' => 'VDF0170', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Porte disque CG125 5T', 'reference' => 'PDC0171', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Porte disque TVS TVS', 'reference' => 'PDT0172', 'prix_achat' => 2000, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Soupape TVS', 'reference' => 'SPT0173', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Soupape CG150', 'reference' => 'SPC0174', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Amortiseur Baja JYC', 'reference' => 'ABJ0174', 'prix_achat' => 7500, 'prix_vente' => 8500, 'image' => null],
    ['nom' => 'Amortiseur Baja & Somon', 'reference' => 'ABS0175', 'prix_achat' => 7500, 'prix_vente' => 8500, 'image' => null],
    ['nom' => 'Amortiseur Baja Isuko', 'reference' => 'ABI0176', 'prix_achat' => 7000, 'prix_vente' => 8000, 'image' => null],
    ['nom' => 'Porte disque 150 4T', 'reference' => 'PDQ0177', 'prix_achat' => 1500, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Porte disque 150 6T 3M', 'reference' => 'PDS0178', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Amponl Clignotant', 'reference' => 'ACL0179', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Amponl Feu Stop', 'reference' => 'AFS0180', 'prix_achat' => 50, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Roulement d\'ambreyag Baja', 'reference' => 'RDB0181', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Chambre a air 250-17 CST', 'reference' => 'CAA0182', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Chambre a air 275-18 CST', 'reference' => 'CHA0183', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Chambre a air 300-18 SM', 'reference' => 'CHA0184', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Piston Jet 150 STD +', 'reference' => 'PST0184', 'prix_achat' => 1800, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Bobine Baja YOG', 'reference' => 'BBY0185', 'prix_achat' => 1200, 'prix_vente' => 1800, 'image' => null],
    ['nom' => 'Piston Baja Baja STD +', 'reference' => 'PBB0185', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston CD110 STD +', 'reference' => 'PCD0186', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston Baja STD + SM', 'reference' => 'PBS0187', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston Baja STD ++', 'reference' => 'PBS0188', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston TVS 160 STD +', 'reference' => 'PTV0189', 'prix_achat' => 1800, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Piston CG150 STD ++', 'reference' => 'PCG0190', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Piston CG150 STD +', 'reference' => 'PCG0191', 'prix_achat' => 1400, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Barque de Chapement 150', 'reference' => 'BDC0191', 'prix_achat' => 45, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Barque de Chapement Baja', 'reference' => 'BCB0192', 'prix_achat' => 40, 'prix_vente' => 150, 'image' => null],
    ['nom' => 'Cale Moteur', 'reference' => 'CMT0193', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pôt feu Stop TVS', 'reference' => 'PFS0194', 'prix_achat' => 2500, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Couvre chaine hight Jack', 'reference' => 'CCH0195', 'prix_achat' => 2500, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Cable d\'accelerateu adapté 3M', 'reference' => 'CDA0196', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Amponl Lazer (bleu)', 'reference' => 'AL0197', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Chambre a air 350-16 CST', 'reference' => 'CHA0198', 'prix_achat' => 1700, 'prix_vente' => 2500, 'image' => null],
    ['nom' => 'Pédale de frein Tvs', 'reference' => 'PDF0199', 'prix_achat' => 1100, 'prix_vente' => 1700, 'image' => null],
    ['nom' => 'Pédale de frein CD110', 'reference' => 'PDF0200', 'prix_achat' => 1000, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Pédale de frein Senke', 'reference' => 'PDF0201', 'prix_achat' => 1100, 'prix_vente' => 1700, 'image' => null],
    ['nom' => 'Pose Pied avant Baja', 'reference' => 'PPA0202', 'prix_achat' => 2300, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Pochette Join Complet TVS', 'reference' => 'PJC0203', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pochette Join Complet CG125', 'reference' => 'PJC0204', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'CDI 150', 'reference' => 'CDI0205', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'CDI 200', 'reference' => 'CDI0206', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Disque Comple Baja YOG', 'reference' => 'DCB0207', 'prix_achat' => 3350, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Disque Complet TVS SM', 'reference' => 'DCT0208', 'prix_achat' => 2800, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Pochette Join CG150', 'reference' => 'PJC0209', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Pochette Join Baja', 'reference' => 'PJB0210', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Porte PPG0211', 'reference' => 'PPG0211', 'prix_achat' => 2300, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Disque Simple Baja YOG', 'reference' => 'DSB0212', 'prix_achat' => 900, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Disque Simple TVS WDFR', 'reference' => 'DST0213', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Disque Simple 150', 'reference' => 'DSP0214', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Boujie D8TC', 'reference' => 'BDA0215', 'prix_achat' => 190, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Boujie A7TC YOG', 'reference' => 'BAS0216', 'prix_achat' => 220, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Boitier 150', 'reference' => 'BTI0217', 'prix_achat' => 2500, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Roulement 6002', 'reference' => 'RLT0218', 'prix_achat' => 0, 'prix_vente' => 300, 'image' => null],
    ['nom' => 'Meter Counter GN', 'reference' => 'MCG0219', 'prix_achat' => 700, 'prix_vente' => 1200, 'image' => null],
    ['nom' => 'Roulement 6302', 'reference' => 'RLT0220', 'prix_achat' => 200, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Roulement 6005', 'reference' => 'RLT0221', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Porte Garniture GN', 'reference' => 'PEG0222', 'prix_achat' => 3000, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Phesean CGL', 'reference' => 'PLC0223', 'prix_achat' => 2600, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Phesean TVS', 'reference' => 'PHT0224', 'prix_achat' => 2700, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Phesean GN', 'reference' => 'PHG0225', 'prix_achat' => 2600, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Phesean Baja', 'reference' => 'PHB0226', 'prix_achat' => 2700, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Poignier d\'allumage GN Côté droit', 'reference' => 'PDG0227', 'prix_achat' => 1100, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Porte Pignon CGL', 'reference' => 'PPC0228', 'prix_achat' => 2500, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Cale Resor CGL', 'reference' => 'CRC0229', 'prix_achat' => 150, 'prix_vente' => 400, 'image' => null],

    ['nom' => 'Arrêt d\'huil 30-43', 'reference' => 'ANL0270', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil 27-37', 'reference' => 'AHL0271', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil 14-28', 'reference' => 'ADH500', 'prix_achat' => 40, 'prix_vente' => 54, 'image' => null],
    ['nom' => 'Arrêt d\'huil Soupape Tvs Origine', 'reference' => 'AHL0272', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé a bougie (Petit)', 'reference' => 'CAB0273', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Bouchong reservoir Senke', 'reference' => 'BAB0274', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Pot Faux stop Baja', 'reference' => 'PFS501', 'prix_achat' => 2200, 'prix_vente' => 2970, 'image' => null],
    ['nom' => 'Lazer tête verte SM', 'reference' => 'LTV502', 'prix_achat' => 1500, 'prix_vente' => 2025, 'image' => null],
    ['nom' => 'Clé 13 a pipe', 'reference' => 'CAP0275', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Portance du haut GN', 'reference' => 'PDH503', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Portance du haut CGL', 'reference' => 'PDH0276', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Porte Pignon P6 GN', 'reference' => 'PPP504', 'prix_achat' => 2300, 'prix_vente' => 3105, 'image' => null],
    ['nom' => 'Portance du bas Complet GN', 'reference' => 'PDB0277', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Portance Tvs', 'reference' => 'DTS0278', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => 'Pédale de frein Senke', 'reference' => 'PFS0279', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'Pédale de frein TVS', 'reference' => 'PDF505', 'prix_achat' => 1100, 'prix_vente' => 1485, 'image' => null],
    ['nom' => 'Ampoul veilleuse (Couleur)', 'reference' => 'AVC0280', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => 'Axe petit pignon GN', 'reference' => 'APP0281', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => 'paire tige Soupape 150/200', 'reference' => 'TSP0282', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Arrêt d\'huil 14-28', 'reference' => 'ADH506', 'prix_achat' => 40, 'prix_vente' => 54, 'image' => null],
    ['nom' => 'Tige de frein Baja', 'reference' => 'TDF0283', 'prix_achat' => 250, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Tige de frein Senke/GN', 'reference' => 'TDF0284', 'prix_achat' => 250, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable de frein Tvs', 'reference' => 'CDF0285', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable d\'acc Tvs', 'reference' => 'CDT0286', 'prix_achat' => 350, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable d\'am Tvc', 'reference' => 'CDT0287', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => 'Cable d\'embrayage GN', 'reference' => 'CDY0288', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Cable d\'ambre 200', 'reference' => 'CDT0289', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => 'Arrêt d\'huil Soupap Complet Baja YOG', 'reference' => 'ASG0247', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Pignon Arrière Baja', 'reference' => 'PAB507', 'prix_achat' => 1200, 'prix_vente' => 1620, 'image' => null],
    ['nom' => 'Moteur Clignotant 150', 'reference' => 'MCL0248', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Arrêt d\'huil soupape gomet', 'reference' => 'ASG0249', 'prix_achat' => 500, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Guide Chain TVS', 'reference' => 'GCT0250', 'prix_achat' => 700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => 'Clé plate 7 plate', 'reference' => 'CAP0251', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 17 a pipe', 'reference' => 'CAP0252', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé 10 a pipe', 'reference' => 'CAP0253', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 18 a pipe', 'reference' => 'CAP0254', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé 12 a pipe', 'reference' => 'CAP0255', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 10 plate', 'reference' => 'CAP0256', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Clé 14 plate', 'reference' => 'CAP0257', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Clé 16 plate', 'reference' => 'CAP0258', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Clé 7 a pipe', 'reference' => 'CAP0259', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Longue 10', 'reference' => 'CNG0260', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Axe de Petit Pignon Baja original', 'reference' => 'APP0261', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Tendeur TVS (de roue)', 'reference' => 'TDT0262', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Abre a Camp Baja Baja', 'reference' => 'AAC0263', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Douille 150', 'reference' => 'DIL0264', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => 'Clé a douille 24', 'reference' => 'CAD0265', 'prix_achat' => 1400, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Clé a douille 30', 'reference' => 'CAD0266', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => 'Clé a douille 20', 'reference' => 'CAD0267', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Clé a douille 13', 'reference' => 'CAD0268', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Contact Complet GN', 'reference' => 'CCG0269', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => 'Marche arrière Comple PM', 'reference' => 'MAC0230', 'prix_achat' => 12500, 'prix_vente' => 13500, 'image' => null],
    ['nom' => 'Bague de chaponem 150', 'reference' => 'BDC508', 'prix_achat' => 450, 'prix_vente' => 607, 'image' => null],
    ['nom' => 'Bague de Chapement Bj', 'reference' => 'BDC509', 'prix_achat' => 40, 'prix_vente' => 54, 'image' => null],
    ['nom' => 'Portance du haut GN', 'reference' => 'PDH0231', 'prix_achat' => 2500, 'prix_vente' => 3300, 'image' => null],
    ['nom' => 'Pot Feux Stop Baja', 'reference' => 'PFS0232', 'prix_achat' => 2200, 'prix_vente' => 2800, 'image' => null],
    ['nom' => 'Chargeur 150', 'reference' => 'CHA510', 'prix_achat' => 700, 'prix_vente' => 945, 'image' => null],
    ['nom' => 'Soupape 150', 'reference' => 'SOU512', 'prix_achat' => 450, 'prix_vente' => 607, 'image' => null],
    ['nom' => 'Soupape Baja YOG', 'reference' => 'SBY0233', 'prix_achat' => 800, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Manette d\'ambreyag Baja', 'reference' => 'MDA513', 'prix_achat' => 0, 'prix_vente' => 0, 'image' => null],
    ['nom' => 'Porté garniture TVS', 'reference' => 'PGT0234', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Pince a Coupé', 'reference' => 'PAC0235', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Petite Pince', 'reference' => 'PPC0236', 'prix_achat' => 600, 'prix_vente' => 1000, 'image' => null],
    ['nom' => 'Grosse Pince', 'reference' => 'GPC0237', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Join de Gorge Chapement noir', 'reference' => 'JDG0238', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => 'Clé Contact CGL', 'reference' => 'CCC514', 'prix_achat' => 1100, 'prix_vente' => 1485, 'image' => null],
    ['nom' => 'Clé Contact Baja SM', 'reference' => 'CCB515', 'prix_achat' => 1500, 'prix_vente' => 2025, 'image' => null],
    ['nom' => 'Porte Retroviseur GN CG', 'reference' => 'PRG0239', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => 'Boulong Porte Pignon TVS', 'reference' => 'PPP0240', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => 'Axe de demareur 150', 'reference' => 'ADD0241', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => 'Clé Contact Baja TVS', 'reference' => 'CCB516', 'prix_achat' => 1500, 'prix_vente' => 2025, 'image' => null],
    ['nom' => 'Balance Baja', 'reference' => 'BBS0242', 'prix_achat' => 2600, 'prix_vente' => 3000, 'image' => null],
    ['nom' => 'Balance 150 CG150 SM', 'reference' => 'BCG0243', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Balance 150 CG150 Ordin', 'reference' => 'BCG0244', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => 'Cylindre 150 SM', 'reference' => 'CSM0245', 'prix_achat' => 7500, 'prix_vente' => 8200, 'image' => null],
    ['nom' => 'Cartere Centrale Complet', 'reference' => 'CCC0245', 'prix_achat' => 24000, 'prix_vente' => 26000, 'image' => null],
    ['nom' => 'Margeur de vitesse GN', 'reference' => 'MDV0246', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],

    // --- Éléments extraits des nouvelles fiches ---
    ['nom' => "Arrêt d'huil Soupape Complet baja", 'reference' => 'ASG0247', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Moteur Clignotant 150", 'reference' => 'MCL0248', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Arrête d'huil soupape gomet", 'reference' => 'ASG0249', 'prix_achat' => 500, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Guide Chain TVS", 'reference' => 'GCT0250', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Clé plate 7 plate", 'reference' => 'CAP0251', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Clé 17 a pipe", 'reference' => 'CAP0252', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Clé 10 a pipe", 'reference' => 'CAP0253', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Clé 18 a pipe", 'reference' => 'CAP0254', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Clé 12 a pipe", 'reference' => 'CAP0255', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Clé 10 plate", 'reference' => 'CAP0256', 'prix_achat' => 300, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Clé 14 plate", 'reference' => 'CAP0257', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Clé 16 plate", 'reference' => 'CAP0258', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Clé 7 a pipe", 'reference' => 'CAP0259', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Longue 10", 'reference' => 'CNG0260', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Axe de Petit Pignon Baja original", 'reference' => 'APP0261', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => "Tendeur TVS (de roue)", 'reference' => 'TDT0262', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Abre a Camp Baja Baja", 'reference' => 'AAC0263', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => "Douille 150", 'reference' => 'DIL0264', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Clé a douille 24", 'reference' => 'CAD0265', 'prix_achat' => 1400, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Clé a douille 30", 'reference' => 'CAD0266', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Clé a douille 10", 'reference' => 'CAD0267', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Clé a douille 13", 'reference' => 'CAD0268', 'prix_achat' => 800, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Contact Complet GN", 'reference' => 'CCG0269', 'prix_achat' => 3000, 'prix_vente' => 3500, 'image' => null],
    ['nom' => "Arrêt d'huil 30-43", 'reference' => 'ANL0270', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Arrêt d'huil 27-37", 'reference' => 'AHL0271', 'prix_achat' => 200, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Arrêt d'huil Soupape Trs Origine", 'reference' => 'AHL0272', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Clé a bougie (Petit)", 'reference' => 'CAB0273', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Bouchong reservoir Senke", 'reference' => 'BAS0274', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "Clé 13 a pipe", 'reference' => 'CAP0275', 'prix_achat' => 350, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Portance du haut CGL", 'reference' => 'PDH0276', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => "Portance du bat Complet GN", 'reference' => 'PDB0277', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => "Portance Tvs", 'reference' => 'DFS0278', 'prix_achat' => 3500, 'prix_vente' => 4000, 'image' => null],
    ['nom' => "Pédale de frein Senke", 'reference' => 'PFS0279', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "Ampoul veilleuse (Compteur)", 'reference' => 'AVC0280', 'prix_achat' => 50, 'prix_vente' => 100, 'image' => null],
    ['nom' => "Axe petit pignon GN", 'reference' => 'APP0281', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "paire tige Soupape 150/200", 'reference' => 'TSP0282', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Tige de frein Baja", 'reference' => 'TDF0283', 'prix_achat' => 250, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Tige de frein Senke/GN", 'reference' => 'TDF0284', 'prix_achat' => 250, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Cable de frein Trs", 'reference' => 'CDF0285', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Cable d'acc Trs", 'reference' => 'CDT0286', 'prix_achat' => 350, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Cable d'am Tvc", 'reference' => 'CDT0287', 'prix_achat' => 400, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Cable d'embreyage GN", 'reference' => 'CDY0288', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable d'ambre 200", 'reference' => 'CDT0289', 'prix_achat' => 500, 'prix_vente' => 900, 'image' => null],
    ['nom' => "Cable d'accélérateur GN", 'reference' => 'CDC0290', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable de frein senke", 'reference' => 'CDF0291', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable d'embreyage Baja", 'reference' => 'CDB0292', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable de Compteur GN", 'reference' => 'CDC0293', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Cable de Moteur GN", 'reference' => 'CDM0294', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Resor Petite bequille GN", 'reference' => 'RPB0295', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Resor Petite bequille Senke", 'reference' => 'RPB0296', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Resor de frein GN", 'reference' => 'RDF0297', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Chambre a air 275-17 SM", 'reference' => 'CHA0298', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Chambre a air 275-18 SM", 'reference' => 'CHA0299', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Garde boue Avant Senke", 'reference' => 'GBA0300', 'prix_achat' => 2700, 'prix_vente' => 3500, 'image' => null],
    ['nom' => "Porte bagage Complet Senke", 'reference' => 'PBC0301', 'prix_achat' => 16500, 'prix_vente' => 18500, 'image' => null],
    ['nom' => "Cable d'acc Baja", 'reference' => 'CDB0302', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable d'embreyage Baja 3M", 'reference' => 'CDB0303', 'prix_achat' => 400, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Cable nue", 'reference' => 'CBN0304', 'prix_achat' => 40, 'prix_vente' => 100, 'image' => null],
    ['nom' => "Gante Baja", 'reference' => 'JNT0305', 'prix_achat' => 18000, 'prix_vente' => 19500, 'image' => null],
    ['nom' => "Gante TVS", 'reference' => 'JTY0306', 'prix_achat' => 18000, 'prix_vente' => 19500, 'image' => null],
    ['nom' => "Fourche avant Trs", 'reference' => 'FAT0307', 'prix_achat' => 16500, 'prix_vente' => 17500, 'image' => null],
    ['nom' => "Fourche avant Baja", 'reference' => 'FAB0308', 'prix_achat' => 16500, 'prix_vente' => 17500, 'image' => null],
    ['nom' => "Marche arriere Comple PM", 'reference' => 'MAC0230', 'prix_achat' => 12500, 'prix_vente' => 13500, 'image' => null],
    ['nom' => "Portance du haut GN", 'reference' => 'PDH0231', 'prix_achat' => 2500, 'prix_vente' => 3300, 'image' => null],
    ['nom' => "Pot Faux Stop Baja", 'reference' => 'PFS0232', 'prix_achat' => 2200, 'prix_vente' => 2800, 'image' => null],
    ['nom' => "Soupape Baja YOG", 'reference' => 'SBY0233', 'prix_achat' => 800, 'prix_vente' => 1300, 'image' => null],
    ['nom' => "Porté garniture TVS", 'reference' => 'PGT0234', 'prix_achat' => 2500, 'prix_vente' => 3000, 'image' => null],
    ['nom' => "Pince a Coupé", 'reference' => 'PAC0235', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => "Petite Pince", 'reference' => 'PPC0236', 'prix_achat' => 600, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Grosse Pince", 'reference' => 'GPC0237', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => "Join de Gorge Chapement noir", 'reference' => 'JDG0238', 'prix_achat' => 100, 'prix_vente' => 200, 'image' => null],
    ['nom' => "Porte Retrovisseur GN CE", 'reference' => 'PRG0239', 'prix_achat' => 350, 'prix_vente' => 700, 'image' => null],
    ['nom' => "Boulong Porte Pignon TVS", 'reference' => 'PPP0240', 'prix_achat' => 250, 'prix_vente' => 500, 'image' => null],
    ['nom' => "Axe de demareur 150", 'reference' => 'ADD0241', 'prix_achat' => 1700, 'prix_vente' => 2200, 'image' => null],
    ['nom' => "Balance Baja", 'reference' => 'BBJ0242', 'prix_achat' => 2600, 'prix_vente' => 3000, 'image' => null],
    ['nom' => "Balance 150 CG150 SM", 'reference' => 'BCG0243', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => "Balance 150 CG150 Ordin", 'reference' => 'BCG0244', 'prix_achat' => 1000, 'prix_vente' => 1300, 'image' => null],
    ['nom' => "Cylindre 150 SM", 'reference' => 'CSM0245', 'prix_achat' => 7500, 'prix_vente' => 8200, 'image' => null],
    ['nom' => "Cartere Centrale Complet", 'reference' => 'CCC0246', 'prix_achat' => 24000, 'prix_vente' => 26000, 'image' => null],
    ['nom' => "Margeur de vitesse GN", 'reference' => 'MDV0246', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Chambre a air 275-18 GST", 'reference' => 'CAH0309', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Chambre a air 350-16 SM", 'reference' => 'CAA0310', 'prix_achat' => 1200, 'prix_vente' => 1500, 'image' => null],
    ['nom' => "Guidon GN (P6)", 'reference' => 'GDN0311', 'prix_achat' => 1700, 'prix_vente' => 2000, 'image' => null],
    ['nom' => "Couvre siege Senke", 'reference' => 'CSS0312', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "Couvre siege GN (P6)", 'reference' => 'CSG0313', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "Couvre siege Baja", 'reference' => 'CSB0314', 'prix_achat' => 1100, 'prix_vente' => 1400, 'image' => null],
    ['nom' => "Axe du pousse", 'reference' => 'ADP0315', 'prix_achat' => 450, 'prix_vente' => 700, 'image' => null],
    ['nom' => "longue clé a boujie", 'reference' => 'LCB0316', 'prix_achat' => 750, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Boulon porte Pignon Senke", 'reference' => 'BPP0317', 'prix_achat' => 250, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Garnitur d'origine Simba", 'reference' => 'GDO0318', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => "Petit Pignon 150", 'reference' => 'PPG0319', 'prix_achat' => 275, 'prix_vente' => 400, 'image' => null],
    ['nom' => "Tandeur chain Motor Baja", 'reference' => 'TCM0319', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Tandeur chaine Moteur TVS", 'reference' => 'TCM0320', 'prix_achat' => 450, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Resort de demareur Baja", 'reference' => 'RDD0321', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Resort de demareur TVS", 'reference' => 'RDD0322', 'prix_achat' => 500, 'prix_vente' => 800, 'image' => null],
    ['nom' => "Renfort Baja", 'reference' => 'RFB0323', 'prix_achat' => 50, 'prix_vente' => 300, 'image' => null],
    ['nom' => "Charbong", 'reference' => 'CHB0324', 'prix_achat' => 700, 'prix_vente' => 1000, 'image' => null],
    ['nom' => "Join Cylindre 150", 'reference' => 'JCD0324', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => "Join Culasse 150", 'reference' => 'JCY0325', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Detergent", 'reference' => 'DTT0326', 'prix_achat' => 37, 'prix_vente' => 50, 'image' => null],
    ['nom' => "Join Cartaire disque TVS", 'reference' => 'JCD0327', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Join Cartaire disque Baja", 'reference' => 'JCD0328', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Join Cartaire bobine Baja", 'reference' => 'JCB0329', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Join Cartaire disque 150", 'reference' => 'JCD0330', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Join Cylindre Baja", 'reference' => 'JCB0331', 'prix_achat' => 45, 'prix_vente' => 100, 'image' => null],
    ['nom' => "Garniture d'origine Baja", 'reference' => 'GDB0332', 'prix_achat' => 1500, 'prix_vente' => 1800, 'image' => null],
    ['nom' => "Join de Culass Baja", 'reference' => 'JDC0333', 'prix_achat' => 75, 'prix_vente' => 150, 'image' => null],
    ['nom' => "Boulong 17/100 Complet", 'reference' => 'BLN0334', 'prix_achat' => 125, 'prix_vente' => 200, 'image' => null],
    ['nom' => "Boulong 13/30", 'reference' => 'BLN0335', 'prix_achat' => 60, 'prix_vente' => 100, 'image' => null],

];
        foreach ($produits as $produit) {
            Produit::firstOrCreate(
                ['reference' => $produit['reference']],
                $produit
            );
        }
    }
}
